on:
  push:
    branches:
      - main
      - master

    




jobs:
  CheckoutAndList:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: List All Files
        run: ls -a 

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Installing Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip        
      
      - name: Installing dependencies
        run: pip install -r requirements.txt
      
      - name: Run Linting
        run: ruff check .

      - name: Ruff format
        run: ruff format .
      - name: Ruff Format check
        run: ruff format --check .
        
      - name: Run Tests 
        working-directory: src
        run: pytest -v      

